portfolio/urls.py
from django.urls import path

from .views import home, about, projects, contact

app_name = 'portfolio'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('projects/', projects, name='projects'),
]

portfolio_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio.views import landing_page

urlpatterns = [
    path("admin/", admin.site.urls),
    path("portfolio/", include('portfolio.urls'), name='portfolio'),
    path('', landing_page)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator, FileExtensionValidator

class Skill(models.Model):
    name = models.CharField(max_length=30)
    mastery = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)])
    logo = models.FileField(upload_to="portfolio/skills", validators=[FileExtensionValidator(['svg', 'jpeg', 'jpg', 'png'])], blank=True)
    
    def __str__(self) -> str:
        return self.name
    

class Project(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    image = models.ImageField(upload_to="portfolio/images", blank=True)
    url = models.URLField(blank=True)
    skills = models.ManyToManyField(Skill)
    
    def __str__(self) -> str:
        return f"{self.id} - {self.title}"
    

class SoftSkill(models.Model):
    name = models.CharField(max_length=40)
    description = models.CharField(max_length=250)
    image = models.FileField(upload_to="portfolio/softskills", validators=[FileExtensionValidator(['svg', 'jpeg', 'jpg', 'png'])], blank=True)
    
    def __str__(self) -> str:
        return self.name
    

portfolio/forms.py
from django import forms

class ContactForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=100, required=True)
    subject = forms.CharField(label="Subject", max_length=200, required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)
    
    

portfolio/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.core.mail import send_mail, BadHeaderError

from .models import Project, Skill
from .forms import ContactForm

def home(request):
    """ Portfolio main page """
    projects = Project.objects.all()
    skills = Skill.objects.all().order_by('-mastery')
    return render(request, 'home.html', context={"projects": projects, "skills": skills})


def landing_page(request):
    return redirect(reverse("portfolio:home"))


def about(request):
    return render(request, 'about.html')


def projects(request):
    projects = Project.objects.all()
    return render(request, 'projects.html', context={"projects": projects})


# def contact(request):
#     # If this is a POST request, the form data needs to be processed.
#     if request.method == "GET":
#         form = ContactForm()    
#     else:
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             subject = form.cleaned_data["subject"]
#             from_email = form.cleaned_data["email"]
#             message = form.cleaned_data["message"]
            
#             try:
#                 send_mail(subject, message, from_email, ["fran.moreno.se@gmail.com"])
#             except BadHeaderError:
#                 return HttpResponse("Invalid header found.")
#             return redirect(reverse("portfolio:home"))
#     return render(request, "contact.html", {"form": form}) 

def contact(request):
    host_mail = "fran.moreno.se@gmail.com"
    return render(request, 'contact.html', context={"host_mail": host_mail})

def thanks(request):
    return render(request, 'thanks.html')
        
    

portfolio/templates/about.html
{% extends 'layout.html' %} {% block content %} {% load static %}

<br><br><br>

<div class="container container-fluid">

    <h1 class="text-xxl-center p-5 m-5">
        Work in progress...
    </h1>
    <!-- <div class="row justify-content-center p-4">
        <div id="quote-section" class="col-9 d-grid align-content-center px-0 rounded-start-5">
            <div class="px-5">
                <p class="text-end">
                    I'm an inquiring and curious person, with a great passion for the things I love. I started to learn about software during my Bachelor's in Robotics Engineering in the University of Málaga. It wasn't until the last year, thanks to a good friend, that I found understood how interesting, beautiful and complex it can be though. From that point, I knew that my carrer would take a turn towards the amusing world of programming.
                </p>
                <p class="text-end">
                    Having the opportunity to bring virtually any idea to life through code is something that not only helps to make life easier, but also to keep your head busy, and understand how things work, by finding the key concepts of it.
                </p>
                <p class="text-end">
                    As you may notice from this introduction, this portfolio is a place in where I would like to unleash my imagination, talk about things I find interesting, and maybe one day to help other people to learn how coding can be introduced to their daily lives.
                </p>
            </div>
        </div>
        <div class="col-3 d-grid justify-content-center align-content-center px-0">
            <img class="rounded-end-5" src="/media/portfolio/images/me.jpg" style="width: 100%;">
        </div>
    </div> -->

    <!-- Carousel -->
    <!-- <div id="myCarousel" class="carousel carousel-dark slide my-5 carousel-custom rounded-5 p-4" data-ride="carousel"> -->
        <!-- Indicators -->
        <!-- <div class="carousel-indicators">
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div> -->
      
        <!-- Wrapper for slides -->
        <!-- <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="row">
                <h1 class="text-center experience-title">My roots</h1>
                <div class="col-lg-5 col-12 d-flex justify-content-center">
                    <img class="rounded-image p-5" src="/media/portfolio/images/malaga.png" height="400px">
                </div>
                <div class="col-lg-7 col-12 d-grid align-content-center justify-content-center">
                    <p>
                        I've been raised in Málaga, located at the very South of Spain. More specifically, in a village called Mijas. Still nowadays, even after visiting and living in different places, it's still my favorite place in the world. Nice people, with a beautiful Spanish accent; great food, like "pescaíto frito"; villages with a lot of history; and really enjoyable shores. 
                    </p>
                    <p>
                        Growing with a humble and lovely family taught me my main values as a person, and drove me to be what I am nowadays. I believe in willingness, honesty and kindness. I also believe in the power of the community, and for that reason, I don't think just for myself, but for people around me.
                    </p>
                    <p>
                        Nowadays, techonology grows really fast. So fast that some people can't keep up. Personally, I would like to contribute to their help by developing software that is useful, but also easy to use. 
                    </p>
                </div>
            </div>
          </div> -->
      
          <!-- <div class="carousel-item">
            <div class="row">
                <h1 class="text-center experience-title">Passions</h1>
                    <div class="text-start">
                        <h3>Basketball</h3>
                        <p>I enjoy sports, but definitely, the one I like the most is basketball. I started to play as a kid, and since then I cannot think about a life without this beautiful sport. One of the best parts of it is the connection you get with the people you play with. </p>
                    </div>
                    <div class="text-end">
                        <h3>Music</h3>
                        <p>I'm always open to listen to some new and different music. Check out some of the songs I'm listening to:</p>
                        <iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/0rye3CoAXmgEL9RyOBQzaJ?utm_source=generator&theme=0" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
                    </div>
                    <div class="text-start">
                        <h3>Traveling</h3>
                        <p>Spain is a really nice place for hikers. Some of the places I've visited:</p>


                    </div>
                </div>
          </div> -->
      
          <!-- <div class="carousel-item">
            <div class="row">
                <h1 class="text-center experience-title">Some of my experiences</h1>
                <div class="col-lg-5 col-12 d-flex justify-content-center">
                    <img class="rounded-image p-5" src="/media/portfolio/images/sample3.jpg"height="400px">
                </div>
                <div class="col-lg-7 col-12 d-grid align-content-center justify-content-center">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ex odio, maximus vel arcu in, porta ultricies urna. Vestibulum tincidunt tempor orci quis eleifend. Nulla vitae enim tempor, placerat ex vitae, suscipit tellus. Donec nec augue ipsum. Ut egestas, tortor ac lacinia accumsan, lorem magna gravida libero, in accumsan sapien eros sed elit. Integer dapibus erat tempus elementum euismod. Phasellus sollicitudin auctor ex, id fermentum augue elementum eget. Phasellus efficitur purus tristique, tempus nulla eget, congue felis.</p>
                </div>
            </div>
        </div> -->
      
        <!-- Left and right controls -->
        <!-- <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
      </div> -->
    
</div>


{% endblock %}

portfolio/templates/contact.html
{% extends 'layout.html' %} {% block content %} {% load static %}

<br><br><br>

<div class="container">

    <div class="row">

        <!-- Reach me section -->
        <div class="col-lg-6 col-12">
            <div>
                <h2 class="section-title">Reach me</h2>
            </div>
            <div id="contact-section" class="p-3">
                <ul class="list-unstyled">
                    <li>
                        <div class="p-3">
                            <img src="/media/portfolio/icons/mail.svg" width="36" style="float: left;"/>
                            <p class="my-1"> fran.moreno.se@gmail.com</p>
                        </div>             
                    </li>
                    <li>
                        <div class="p-3">
                            <img src="/media/portfolio/icons/phone.svg" width="36" style="float: left;"   />
                            <p class="my-1"> (+34) 678 12 72 97</p>
                        </div>
                    </li>
                    <li>
                        <a href="https://www.linkedin.com/in/franciscomorenorodgiruez/" target="_blank" class="d-inline-block justify-content-center p-3">
                            <img src="/media/portfolio/icons/linkedin.svg" width="36" style="float: left;"   />
                            <p class="my-1">Francisco Moreno Rodríguez</p>
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/Franm99" target="_blank" class="d-inline-block justify-content-center p-3">
                            <img src="/media/portfolio/icons/github.svg"  height="36" style="float: left;"   />
                            <p class="my-1">Franm99</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <!-- Send email section -->
        <div class="col-lg-6 col-12">
            <h2 class="section-title">Or send me an Email</h2>

            <form id="formMail" title="Contact me">
                <div class="form-group my-2">
                    <label for="subject">Subject</label>
                    <input type="text" class="form-control" name="subject" maxlength="200" required id="subject" placeholder="Topic of your message">
                </div>
                <div class="form-group my-2">
                    <label for="message">Message</label>
                    <textarea class="form-control" name="message" cols="40" rows="7" required id="message"></textarea>
                </div>
            </form>
        
            <button id="button-submit" class="rounded-1 px-4 py-2 my-2 " onclick="sendMail('{{ host_mail }}')">Send</button>
        </div>
    </div>


    <!-- Javascript -->
    <script>
        function sendMail(email_to) {
            form = document.getElementById("formMail");
            subject = form.subject.value; 
            message = form.message.value; 
            emailCC = ''

            window.location.href = "mailto:" + email_to + "?" + 
                                    (emailCC ? "cc=" + emailCC : "") + 
                                    (subject ? "&subject=" + subject : "") + 
                                    (message ? "&body=" + message : "");
            
        } 
    </script>

</div>



{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %} {% block content %} {% load static %}

<section id="welcome" class="d-flex flex-column justify-content-center">
  <div class="col-md-6 py-5 p-5" style="background-color: white">
    <h1 class="py-2">Francisco Moreno</h1>
    <p>Software Engineer</p>
  </div>
</section>

<section id="skills" class="row py-3 justify-content-center">
  <div class="col-md-8">
    <ul
      class="list-inline list-group-custom justify-content-center align-content-center"
    >
      {% for skill in skills %}
      <li class="mx-3">
        <img
          class="grow-big"
          src="{{skill.logo.url}}"
          width="50"
          height="50"
        />
      </li>
      {% endfor %}
    </ul>
  </div>
</section>

<div class="container container-fluid">
  <div class="row justify-content-center p-4">
    <h2 class="section-title">About me</h2>
      <div id="quote-section" class="col-9 d-grid align-content-center px-0 rounded-start-5">
          <div class="px-5">
              <p class="text-end">
                  I'm an inquiring and curious person, with a great passion for the things I love. I started to learn about software during my Bachelor's in Robotics Engineering in the University of Málaga. It wasn't until the last year, thanks to a good friend, that I found understood how interesting, beautiful and complex it can be though. From that point, I knew that my carrer would take a turn towards the amusing world of programming.
              </p>
              <p class="text-end">
                  Having the opportunity to bring virtually any idea to life through code is something that not only helps to make life easier, but also to keep your head busy, and understand how things work, by finding the key concepts of it.
              </p>
              <p class="text-end">
                  As you may notice from this introduction, this portfolio is a place in where I would like to unleash my imagination, talk about things I find interesting, and maybe one day to help other people to learn how coding can be introduced to their daily lives.
              </p>
          </div>
      </div>
      <div class="col-3 d-grid justify-content-center align-content-center px-0">
          <img class="rounded-end-5" src="/media/portfolio/images/me.jpg" style="width: 100%;">
      </div>
  </div>

<div class="container">
  <div class="row my-4 justify-content-center">
    <h2 class="section-title">Projects</h2>
  
    {% for project in projects %}
  
    <div class="col-md-4 p-4">
      <div class="card grow-small card-project">
        <img
          class="card-img-top"
          style="width: 100%; height: 20vw; object-fit: cover"
          src="{{project.image.url}}"
          alt="{{project.title}}"
        />
  
        <div class="card-header card-header-custom">
            {{project.title}}
        </div>

        <div class="card-body">
          <ul class="list-inline list-group-custom justify-content-center align-content-center">
            {% for skill in project.skills.all %}
            
            <li class="mx-2">
              <img src="{{ skill.logo.url }}" width='20' height='20' />
            </li>
            
            {% endfor %}
          </ul>
  
          {% if project.url %}
  
          <a
            href="{{project.url}}"
            class="btn btn-light rounded-0 btn-sm"
            target="_blank" >
              <span class="material-symbols-outlined">
                open_in_new
              </span>
          </a>
  
          {% endif %}
        </div>
      </div>
    </div>
  
    {% endfor %}
  </div>
</div>

{% endblock %}

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-witdh, initial-scale=1.0" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'main.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Croissant+One&family=Josefin+Sans&display=swap"
      rel="stylesheet"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Croissant+One&family=Josefin+Sans&family=Lemonada:wght@500&display=swap" rel="stylesheet">
    

<!-- Icons -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

<!-- Favicon -->
<link rel="shortcut icon" type="image/svg" href="{% static 'portfolio/favicon.svg' %}">


<title>My Portfolio</title>
  </head>
  <body style="background-color: white;">
    {% include 'partials/_navbar.html' %}

    <div>{% block content %} {% endblock %}</div>

    {% include 'partials/_footer.html' %}
  
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/partials/_footer.html
{% load static %}

<div class="footer-custom">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4">
      <div class="col-md-4 d-flex align-items-center px-5">
        <span 
          class="mb-3 mb-md-0"
          style="color: #24585A;">
          Francisco Moreno
        </span>
      </div>
  
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex align-items-end px-5">
        <li class="ms-3"><a href="https://www.linkedin.com/in/franciscomorenorodgiruez/"><img src="/media/portfolio/icons/linkedin.svg" width="36"   /></a></li>
        <li class="ms-3"><a href="https://github.com/Franm99"><img src="/media/portfolio/icons/github.svg"  height="36"   /></a></li>
      </ul>
    </footer>
  </div>

portfolio/templates/partials/_navbar.html
{% load static %}

<header id="header">
  <div>
    <nav id="navbar" class="nav-menu navbar align-content-center navbar-custom">
      <!-- todo: id not working, transition never happens. -->
      <a
        id="brand-icon"  
        class="navbar-brand px-5"
        href="/"
        >F. M.</a
      >

      <div class="justify-content-end align-content-center mx-5">
        <ul class="list-inline navbar-items mb-0 align-content-center">
          <li class="nav-link mx-2 grow-small"><a class="nav-link" href="{% url 'portfolio:home' %}">Home</a></li>
          <li class="nav-link mx-2 grow-small"><a class="nav-link" href="{% url 'portfolio:about' %}">About</a></li>
          <li class="nav-link mx-2 grow-small"><a class="nav-link" href="{% url 'portfolio:projects' %}">Projects</a></li>
          <li class="nav-link mx-2 grow-small"><a class="nav-link" href="{% url 'portfolio:contact' %}">Contact</a></li>
          <li class="nav-link mx-2">
            <a
              id="cv-button"
              class="btn btn-primary btn-sm d-flex"
              href="{% static 'portfolio/cv.pdf' %}"
              target="_blank"
              >Download CV</a
            >
          </li>
        </ul>
      </div>
    </nav>
  </div>
</header>

portfolio/templates/projects.html
{% extends 'layout.html' %} {% block content %} {% load static %}

<br><br><br>

{% for project in projects %}

<div class="px-5 py-3">
    <div class="card card-body card-body-custom" onclick="window.open('{{project.url}}')">
        
        <div class="row">
            <div class="col-lg-3 col-12">
                <img src="{{project.image.url}}" class="img-fluid rounded-2">
            </div>

            <div class="col-lg-9 col-12">
                <h2 class="project-title">{{project.title}}</h2>
                <p class="m-2">{{project.description}}</p>

                <div class="row my-3">
                    <div class="col-6 align-content-center">
                        <h4 class="project-title">Skills/Technologies:</h4>
                    </div>
                    <div class="col-6 align-content-center justify-content-center">
                        <ul class="list-inline list-group-custom align-content-center m-2">
                            {% for skill in project.skills.all %}
        
                            <li class="mx-2">
                                <img src="{{skill.logo.url}}" width="36" height="36">
                            </li>
        
                            {% endfor %}
                        </ul>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

{% endfor %}

{% endblock %}

portfolio/templates/thanks.html
{% extends 'layout.html' %} {% block content %} {% load static %}

<br><br><br>


{% endblock %}